### ISSUE TITLE
kelas

### ISSUE THREAD

**Issue by padlianch** [padlianch/bootcamp3#2]
<img width="254" alt="image" src="https://github.com/padlianch/bootcamp3/assets/24665491/6c600872-4e69-4e84-b462-39f9c5b4b752">

**Comment by edwardferdian78** [comment]
CREATE TABLE kelas(
 	id int NOT NULL,
	id_tingkat_kelas INT,
	id_tahun_ajaran INT,
	id_ruangan INT,
	nama_kelas VARCHAR(255),
	id_wali_kelas INT,
 	PRIMARY KEY (id)
);
