### ISSUE TITLE
kelas mata pelajaran

### ISSUE THREAD

**Issue by padlianch** [padlianch/bootcamp3#4]
<img width="300" alt="image" src="https://github.com/padlianch/bootcamp3/assets/24665491/608a87ee-4fe5-475a-bec5-81aee2b52d8b">

**Comment by KEVIN3011** [comment]
CREATE TABLE kelas mata pelajaran(
-- 	id int NOT NULL,
-- 	id_kelas int NOT NULL,
-- 	id_mata_pelajaran varchar(255),
--      id_guru
-- 	PRIMARY KEY (id)l

**Comment by KEVIN3011** [comment]
CREATE TABLE kelas mata pelajaran(
-- id int NOT NULL,
-- id_kelas int NOT NULL,
-- id_mata_pelajaran varchar(255),
-- id_guru
-- PRIMARY KEY (id)

**Comment by KEVIN3011** [comment]
CREATE TABLE kelas mata pelajaran(
-- id int NOT NULL,
-- id_kelas int NOT NULL,
-- id_mata_pelajaran varchar(255),
-- id_guru int,
-- PRIMARY KEY (id)

**Comment by KEVIN3011** [comment]
CREATE TABLE kelas_mata_pelajaran(
 	id int NOT NULL,
	id_kelas INT,
	id_mata_pelajaran VARCHAR(255),,
	id_guru INT,
 	PRIMARY KEY (id)
);
