### ISSUE TITLE
siswa kelas riwayat

### ISSUE THREAD

**Issue by padlianch** [padlianch/bootcamp3#5]
<img width="235" alt="image" src="https://github.com/padlianch/bootcamp3/assets/24665491/125dfb64-a24a-43f0-8165-db2c7732fe4c">

**Comment by edwardferdian78** [comment]
CREATE TABLE siswa_kelas_riwayat(
 	id int NOT NULL,
	id_siswa INT,
	id_kelas INT,
 	PRIMARY KEY (id)
);
