### ISSUE TITLE
mata pelajaran

### ISSUE THREAD

**Issue by padlianch** [padlianch/bootcamp3#6]
<img width="287" alt="image" src="https://github.com/padlianch/bootcamp3/assets/24665491/61dcfb00-1a25-41ef-a650-02d9194ae063">

**Comment by edwardferdian78** [comment]
CREATE TABLE mata_pelajaran(
 	id int NOT NULL,
	id_tahun_ajaran INT,
	id_tingkat INT,
	mata_pelajaran VARCHAR(255),
 	PRIMARY KEY (id)
);
