### ISSUE TITLE
guru mata pelajaran

### ISSUE THREAD

**Issue by padlianch** [padlianch/bootcamp3#7]
<img width="197" alt="image" src="https://github.com/padlianch/bootcamp3/assets/24665491/ba2e5e87-0cd0-46fc-939b-488f632a651d">

**Comment by edwardferdian78** [comment]
CREATE TABLE guru_mata_pelajaran(
 	id int NOT NULL,
	id_guru INT,
	id_mata_pelajaran INT,
 	PRIMARY KEY (id)
);
